### ISSUE TITLE
pyenv is not put in PATH

### ISSUE THREAD

**Issue by alexey-guryanov** [dirn/ansible-pyenv#3] opened 2015-06-24 20:15 UTC
Even though there is a task putting pyenv bin directory into PATH, but the code it produces is executed only if pyenv is already in PATH (basically it is never executed):

```
    - if which pyenv > /dev/null; then
    - "    export PYENV_ROOT=\\\"$HOME/.pyenv\\\""
    - "    export PATH=\\\"$PYENV_ROOT/bin:$PATH\\\""
    - "    eval \\\"$(pyenv init -)\\\""
    - "fi # pyenv"
```

**Comment by blueyed** [comment] 2015-07-08 19:23
Yep, seems to be duplicate of #1.

**Comment by dirn** [comment] 2015-10-09 15:42
Closing as duplicate.

**Closed as completed by dirn** 2015-10-09 15:42 UTC
